version: "3"

services:
  # Serviço que irá rodar o node
  backend:
    # Imagem base do container
    build: ./backend
    # Nome do container para facilitar execução
    container_name: blitz-back
    # Mesmo que `docker run -t`
    tty: true
    # Mesmo que `docker run -i`
    stdin_open: true
    # Substitui o comando padrão da imagem do node
    command: bash
    # Restarta a imagem caso algo a faça parar
    restart: always
    # Diretório padrão de execução
    working_dir: /app
    # Lista de volumes (diretórios) mapeados de fora para dentro do container
    volumes:
      # Monta o diretório atual, com todos os dados do projeto, 
      # dentro do diretório /app
      - ./backend:/app
    # Lista de portas mapeadas de dentro para fora do container
    # na notação porta_de_fora:porta_de_dentro
    ports:
      # Expõe a porta padrão da aplicação: altere aqui caso use outra porta
      - 3001:3001
    environment:
      PORT: 3001
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: db
      DB_NAME: Tasks
      DB_PORT: 3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"] # Caso utilize outra porta interna para o back, altere ela aqui também
      timeout: 10s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: blitz-front
    ports:
      - 3000:3000
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]  # Caso utilize outra porta interna para o front, altere ela aqui também
      timeout: 15s
      retries: 7
    command: npm start

  # Serviço que irá rodar o banco de dados
  db:
    container_name: blitz-db
    image: mysql:5.7
    restart: always
    # Lista de portas mapeadas de dentro para fora do container
    # na notação porta_de_fora:porta_de_dentro
    ports:
      # Expõe a porta padrão do banco de dados
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE # Deve omitir alertas menores
